project:
  type: website
  output-dir: ./docs

website:
  page-navigation: true
  search: true
  # title: "Ed Henry"
  navbar:
    # background: dark
    # logo: quarto.png
    logo-alt: ""
    title: false
    collapse-below: lg
    left:
      - text: "Me"
        href: index.qmd
      - text: "Projects"
        href: projects/projects.qmd
      - text: "Talks"
        href: talks/talks.qmd
      - text: "Notes"
        href: notes/notes.qmd

    right:
      - about.qmd
      - icon: github
        href: https://github.com/edhenry
      - icon: twitter
        href: https://twitter.com/edhenry_
  page-footer:
    # left: |

    center:
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/edhenry
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/edhenry_
format:
  html:
    theme:
      light:
        - cosmo
        # - custom.scss
      dark: [slate, theme-dark.css]
    # # css: styles.css
    toc: true
    # code-tools: true
    highlight-style: a11y-dark
    # code-block-bg: "#d3d8df"
    # code-block-border-left: "#041f58"
    # code-block-border-left-size: "4px"
    code-overflow: wrap
    # code-block-bg-alpha: .8
