project:
  type: website
  output-dir: ./docs

website:
  title: "Ed Henry"
  description: "Research notes on modularity and compositionality in artificial intelligence."
  page-navigation: true
  search: true
  navbar:
    logo-alt: ""
    title: "Ed Henry"
    collapse-below: lg
    left:
      - text: "Research"
        href: research.qmd
      - text: "Notes"
        href: notes.qmd
      - text: "Projects"
        href: projects/projects.qmd
      - text: "Talks"
        href: talks/talks.qmd
      - text: "Quotes"
        href: quotes.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/edhenry
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/edhenry_
        aria-label: Twitter
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Quotes"
        href: quotes.qmd
    right:
      - icon: github
        href: https://github.com/edhenry
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/edhenry_
        aria-label: Twitter

format:
  html:
    theme:
      light: cosmo
      dark: [slate, theme-dark.css]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    highlight-style: a11y-dark
    code-overflow: wrap
    citations-hover: true
    crossrefs-hover: true
    link-external-newwindow: true
    number-sections: false
