# Site settings
title: Ed Henry's Blog
header-img: "img/galaxy.jpg"
email: edward.m.henry@gmail.com
copyright_name: Ed Henry
description: "A place for me to keep notes about what I know that hopefully someone else finds useful"
baseurl: ""
url: "http://edhenry.github.io"
twitter_username: EdHenry_
github_username:  edhenry
facebook_username:  
email_username:  edward.m.henry@gmail.com
theme: "ed."


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
